services:
    perfumery-client-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file:
            - .env.dev
        extra_hosts:
            - "minio.perfumesdelpuro.com:172.17.0.1"
        container_name: perfumery-client
        ports:
            - "4002:4002"
        environment:
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://perfumery-api.onrender.com/}
            - AUTH_SECRET=${AUTH_SECRET:-kagkhasghdgakjdghakghdkajgdkjasgdkagsdjgasjgdasdkgajdgaks}
            - NODE_ENV=production
            - AUTH_MODE=${AUTH_MODE:-dev}
            - NEXT_PUBLIC_IMAGE_HOST=${NEXT_PUBLIC_IMAGE_HOST:-localhost}
            - NEXT_PUBLIC_IMAGE_PORT=${NEXT_PUBLIC_IMAGE_PORT:-9000}
            - NEXT_PUBLIC_WHATS_APP_PHONE_NUMBER=${NEXT_PUBLIC_WHATS_APP_PHONE_NUMBER:-56884181}
        restart: unless-stopped
        networks:
            - perfumery-network

networks:
    perfumery-network:
        name: perfumery-network
